services:
  - type: web
    name: guardplus-api
    env: python
    plan: free
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URI
        scope: build,runtime
      - key: GROQ_API_KEY
        scope: build,runtime
